"""Fast, fail-safe 2-D overlap alignment for approximate image mosaics.

GPS-derived image centres and metadata-derived ground footprints provide the
initial layout. Only likely overlapping neighbours are compared. ORB points
are supplemented with descriptors at endpoints and midpoints of long image
structures, then filtered by the GPS prior. A partial-affine RANSAC fit supplies
a robust centre-to-centre constraint. Only mutually supported components are
solved, with soft GPS anchors, so errors do not accumulate sequentially.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
from pathlib import Path
from typing import Any, Callable, Optional

import cv2
import numpy as np
from PIL import Image


ANALYSIS_MAX_DIMENSION = 800
MAX_NEIGHBOURS = 8
MIN_RATIO_MATCHES = 12
MIN_RANSAC_INLIERS = 8
MAX_PAIR_ROTATION_DEG = 4.0
MAX_PAIR_RMS_PX = 6.0
MIN_PAIR_SCALE = 0.94
MAX_PAIR_SCALE = 1.06


@dataclass(frozen=True)
class ImagePlacement:
    name: str
    path: Path
    center_x: float
    center_y: float
    width: int
    height: int


@dataclass
class _Features:
    placement: ImagePlacement
    points: np.ndarray
    descriptors: Optional[np.ndarray]
    fingerprint: str
    orb_point_count: int
    structural_point_count: int
    long_line_count: int


def _long_line_keypoints(gray: np.ndarray, mask: np.ndarray) -> tuple[list[cv2.KeyPoint], int]:
    """Return endpoints/midpoints of long structures without modifying the source image."""
    detector = cv2.createLineSegmentDetector(cv2.LSD_REFINE_STD)
    detected = detector.detect(gray)[0]
    if detected is None:
        return [], 0
    minimum_length = max(18.0, min(gray.shape) * 0.10)
    points: list[tuple[float, float]] = []
    line_count = 0
    for raw_line in detected[:, 0, :]:
        x1, y1, x2, y2 = map(float, raw_line)
        if float(np.hypot(x2 - x1, y2 - y1)) < minimum_length:
            continue
        line_count += 1
        points.extend(((x1, y1), (x2, y2), ((x1 + x2) / 2.0, (y1 + y2) / 2.0)))
    # Quantization removes repeated endpoints generated by neighbouring line fragments.
    unique = sorted({(round(x / 3.0) * 3.0, round(y / 3.0) * 3.0) for x, y in points})[:700]
    keypoints = [
        cv2.KeyPoint(x, y, 20.0)
        for x, y in unique
        if 16 <= x < gray.shape[1] - 16
        and 16 <= y < gray.shape[0] - 16
        and mask[int(round(y)), int(round(x))] > 0
    ]
    return keypoints, line_count


def _extract_features(placement: ImagePlacement) -> _Features:
    with Image.open(placement.path) as image:
        rgba = np.asarray(image.convert("RGBA"), dtype=np.uint8)
    gray = cv2.cvtColor(rgba[:, :, :3], cv2.COLOR_RGB2GRAY)
    alpha = rgba[:, :, 3]
    scale = min(1.0, ANALYSIS_MAX_DIMENSION / max(gray.shape))
    if scale < 1.0:
        gray = cv2.resize(gray, None, fx=scale, fy=scale, interpolation=cv2.INTER_AREA)
        alpha = cv2.resize(alpha, (gray.shape[1], gray.shape[0]), interpolation=cv2.INTER_NEAREST)
    gray = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8)).apply(gray)
    mask = np.where(alpha > 32, 255, 0).astype(np.uint8)
    fingerprint = hashlib.blake2b(gray.tobytes(), digest_size=16).hexdigest()
    detector = cv2.ORB_create(
        nfeatures=1800,
        scaleFactor=1.2,
        nlevels=8,
        edgeThreshold=15,
        fastThreshold=10,
    )
    keypoints, descriptors = detector.detectAndCompute(gray, mask)
    orb_count = len(keypoints or [])
    structural_keypoints, long_line_count = _long_line_keypoints(gray, mask)
    structural_descriptors = None
    if structural_keypoints:
        structural_keypoints, structural_descriptors = detector.compute(gray, structural_keypoints)
    structural_count = len(structural_keypoints or [])
    if structural_descriptors is not None and structural_count:
        keypoints = list(keypoints or []) + list(structural_keypoints)
        descriptors = (
            structural_descriptors
            if descriptors is None
            else np.vstack((descriptors, structural_descriptors))
        )
    if not keypoints:
        return _Features(
            placement, np.empty((0, 2), dtype=np.float64), None,
            fingerprint, 0, 0, long_line_count,
        )
    with Image.open(placement.path) as source_image:
        source_width, source_height = source_image.size
    coordinate_scale = np.asarray([
        placement.width / max(1.0, float(source_width)),
        placement.height / max(1.0, float(source_height)),
    ])
    points = (np.asarray([point.pt for point in keypoints], dtype=np.float64) / scale) * coordinate_scale
    return _Features(
        placement, points, descriptors, fingerprint,
        orb_count, structural_count, long_line_count,
    )


def _overlap_candidates(placements: list[ImagePlacement]) -> list[tuple[int, int]]:
    candidates: set[tuple[int, int]] = set()
    for first_index, first in enumerate(placements):
        neighbours: list[tuple[float, int]] = []
        for second_index, second in enumerate(placements):
            if first_index == second_index:
                continue
            dx = abs(second.center_x - first.center_x)
            dy = abs(second.center_y - first.center_y)
            # A small margin tolerates ordinary consumer-GPS error while still
            # preventing unrelated repeated panel rows from being compared.
            if dx > (first.width + second.width) * 0.60:
                continue
            if dy > (first.height + second.height) * 0.60:
                continue
            neighbours.append((float(np.hypot(dx, dy)), second_index))
        for _distance, second_index in sorted(neighbours)[:MAX_NEIGHBOURS]:
            candidates.add(tuple(sorted((first_index, second_index))))
    return sorted(candidates)


def _match_pair(first: _Features, second: _Features) -> tuple[Optional[dict[str, Any]], dict[str, Any]]:
    record: dict[str, Any] = {
        "first": first.placement.name,
        "second": second.placement.name,
        "first_orb_points": first.orb_point_count,
        "second_orb_points": second.orb_point_count,
        "first_structural_points": first.structural_point_count,
        "second_structural_points": second.structural_point_count,
        "first_long_lines": first.long_line_count,
        "second_long_lines": second.long_line_count,
    }
    if first.fingerprint == second.fingerprint:
        record.update(
            status="rejected_duplicate",
            reason="Prepared images are pixel-identical and cannot provide an independent position constraint.",
        )
        return None, record
    if first.descriptors is None or second.descriptors is None:
        record.update(status="rejected_no_features", reason="One image has no usable visual features.")
        return None, record
    matcher = cv2.BFMatcher(cv2.NORM_HAMMING)
    pairs = matcher.knnMatch(first.descriptors, second.descriptors, k=2)
    ratio_matches = [
        pair[0]
        for pair in pairs
        if len(pair) == 2 and pair[0].distance < 0.74 * pair[1].distance
    ]
    unique_matches = []
    used_second_features: set[int] = set()
    for match in sorted(ratio_matches, key=lambda item: item.distance):
        if match.trainIdx in used_second_features:
            continue
        used_second_features.add(match.trainIdx)
        unique_matches.append(match)
    ratio_matches = unique_matches
    record["ratio_match_count"] = len(ratio_matches)
    if len(ratio_matches) < MIN_RATIO_MATCHES:
        record.update(status="rejected_few_matches", reason="Too few distinctive feature matches.")
        return None, record

    first_center = np.asarray([first.placement.width / 2.0, first.placement.height / 2.0])
    second_center = np.asarray([second.placement.width / 2.0, second.placement.height / 2.0])
    expected = np.asarray([
        second.placement.center_x - first.placement.center_x,
        second.placement.center_y - first.placement.center_y,
    ])
    first_points = np.asarray([first.points[m.queryIdx] for m in ratio_matches]) - first_center
    second_points = np.asarray([second.points[m.trainIdx] for m in ratio_matches]) - second_center
    measured = first_points - second_points
    gate = max(45.0, min(first.placement.width, first.placement.height) * 0.28)
    gps_ok = np.linalg.norm(measured - expected, axis=1) <= gate
    first_points = first_points[gps_ok]
    second_points = second_points[gps_ok]
    record["gps_consistent_match_count"] = int(np.sum(gps_ok))
    record["gps_gate_px"] = round(gate, 3)
    if len(first_points) < MIN_RATIO_MATCHES:
        record.update(status="rejected_gps_conflict", reason="Feature matches conflict with the GPS-predicted overlap.")
        return None, record

    transform, inlier_mask = cv2.estimateAffinePartial2D(
        second_points,
        first_points,
        method=cv2.RANSAC,
        ransacReprojThreshold=4.0,
        maxIters=2500,
        confidence=0.995,
        refineIters=20,
    )
    if transform is None or inlier_mask is None:
        record.update(status="rejected_ransac", reason="No stable overlap transform was found.")
        return None, record
    inliers = inlier_mask.ravel().astype(bool)
    inlier_count = int(np.sum(inliers))
    record["ransac_inlier_count"] = inlier_count
    if inlier_count < MIN_RANSAC_INLIERS:
        record.update(status="rejected_few_inliers", reason="Too few RANSAC-supported correspondences.")
        return None, record

    a, b = float(transform[0, 0]), float(transform[1, 0])
    scale = float(np.hypot(a, b))
    rotation = float(np.degrees(np.arctan2(b, a)))
    delta = np.asarray(transform[:, 2], dtype=np.float64)
    predicted = cv2.transform(second_points[inliers].reshape(-1, 1, 2), transform).reshape(-1, 2)
    residuals = np.linalg.norm(predicted - first_points[inliers], axis=1)
    rms = float(np.sqrt(np.mean(np.square(residuals))))
    record.update(
        scale=round(scale, 6),
        relative_rotation_deg=round(rotation, 6),
        reprojection_rms_px=round(rms, 6),
        measured_center_delta_px=[round(float(delta[0]), 6), round(float(delta[1]), 6)],
        gps_center_delta_px=[round(float(expected[0]), 6), round(float(expected[1]), 6)],
    )
    first_span = np.ptp(first_points[inliers], axis=0)
    second_span = np.ptp(second_points[inliers], axis=0)
    coverage = [
        min(float(first_span[0] / first.placement.width), float(second_span[0] / second.placement.width)),
        min(float(first_span[1] / first.placement.height), float(second_span[1] / second.placement.height)),
    ]
    record["inlier_coverage"] = [round(value, 6) for value in coverage]
    if max(coverage) < 0.30 or min(coverage) < 0.06:
        record.update(status="rejected_clustered_inliers", reason="RANSAC matches cover too little of the overlap.")
        return None, record
    if rms > MAX_PAIR_RMS_PX:
        record.update(status="rejected_high_error", reason="Overlap reprojection error is too high.")
        return None, record
    if not MIN_PAIR_SCALE <= scale <= MAX_PAIR_SCALE:
        record.update(status="rejected_scale", reason="Overlap implies an unsafe scale change.")
        return None, record
    if abs(rotation) > MAX_PAIR_ROTATION_DEG:
        record.update(status="rejected_rotation", reason="Overlap implies too much residual rotation for a fast planar refinement.")
        return None, record
    if np.linalg.norm(delta - expected) > gate:
        record.update(status="rejected_displacement", reason="Refined placement is too far from its GPS anchor.")
        return None, record

    weight = min(4.0, max(0.5, inlier_count / 12.0)) / max(1.0, rms)
    constraint = {
        "dx": float(delta[0]),
        "dy": float(delta[1]),
        "rotation_deg": rotation,
        "weight": weight,
        "inliers": inlier_count,
    }
    record.update(status="accepted", weight=round(weight, 6))
    return constraint, record


def _solve_axis(initial: np.ndarray, edges: list[tuple[int, int, float, float]]) -> np.ndarray:
    count = len(initial)
    rows: list[np.ndarray] = []
    values: list[float] = []
    # Soft priors retain the absolute geolocation and stabilize disconnected images.
    for index, value in enumerate(initial):
        row = np.zeros(count, dtype=np.float64)
        row[index] = 0.25
        rows.append(row)
        values.append(float(value) * 0.25)
    for first, second, delta, weight in edges:
        row = np.zeros(count, dtype=np.float64)
        root_weight = float(np.sqrt(max(weight, 1e-6)))
        row[first] = -root_weight
        row[second] = root_weight
        rows.append(row)
        values.append(float(delta) * root_weight)
    return np.linalg.lstsq(np.vstack(rows), np.asarray(values), rcond=None)[0]


def refine_mosaic_placements(
    placements: list[ImagePlacement],
    log: Optional[Callable[[str], None]] = None,
) -> tuple[dict[str, tuple[float, float]], dict[str, Any]]:
    """Return globally refined centres and a serializable alignment report."""
    emit = log or (lambda _message: None)
    report: dict[str, Any] = {
        "method": "GPS-anchored hybrid ORB and long-line structural points with partial-affine RANSAC",
        "image_count": len(placements),
        "maximum_neighbours_per_image": MAX_NEIGHBOURS,
        "pairs": [],
    }
    if len(placements) < 2:
        report.update(status="skipped", reason="At least two placed images are required.")
        return {item.name: (item.center_x, item.center_y) for item in placements}, report

    emit(f"Extracting point and long-line structural features from {len(placements)} geolocated image(s)…")
    features = []
    progress_step = max(1, len(placements) // 10)
    for index, item in enumerate(placements, start=1):
        features.append(_extract_features(item))
        if index % progress_step == 0 or index == len(placements):
            emit(f"Feature extraction progress: {index}/{len(placements)} image(s)")
    pairs = _overlap_candidates(placements)
    report["candidate_pair_count"] = len(pairs)
    emit(f"Checking {len(pairs)} likely GPS-neighbour overlap pair(s)…")
    constraints: list[tuple[int, int, dict[str, Any]]] = []
    for pair_index, (first_index, second_index) in enumerate(pairs, start=1):
        constraint, pair_record = _match_pair(features[first_index], features[second_index])
        report["pairs"].append(pair_record)
        if constraint is None:
            emit(
                f"Overlap {pair_index}/{len(pairs)} rejected: "
                f"{placements[first_index].name} ↔ {placements[second_index].name}: "
                f"{pair_record.get('reason', pair_record.get('status'))}"
            )
            continue
        constraints.append((first_index, second_index, constraint))
        emit(
            f"Overlap {pair_index}/{len(pairs)} accepted: "
            f"{placements[first_index].name} ↔ {placements[second_index].name}: "
            f"inliers={constraint['inliers']}, RMS={pair_record['reprojection_rms_px']:.2f}px"
        )

    if not constraints:
        report.update(
            status="gps_only",
            accepted_pair_count=0,
            reason="No overlap pair passed validation; all images retain GPS placement.",
        )
        emit("No overlap pair passed validation; retaining GPS placement for every image.")
        return {item.name: (item.center_x, item.center_y) for item in placements}, report

    # A lone pair is too easy to confuse on repeated panel rows. Only components
    # supported by at least three images are allowed to move; other accepted
    # pair estimates remain recorded for diagnosis but retain GPS placement.
    adjacency: dict[int, set[int]] = {index: set() for index in range(len(placements))}
    for first_index, second_index, _item in constraints:
        adjacency[first_index].add(second_index)
        adjacency[second_index].add(first_index)
    supported_nodes: set[int] = set()
    visited: set[int] = set()
    for start in range(len(placements)):
        if start in visited or not adjacency[start]:
            continue
        stack = [start]
        component: set[int] = set()
        while stack:
            current = stack.pop()
            if current in component:
                continue
            component.add(current)
            stack.extend(adjacency[current] - component)
        visited.update(component)
        if len(component) >= 3:
            supported_nodes.update(component)
    supported_constraints = [
        item for item in constraints if item[0] in supported_nodes and item[1] in supported_nodes
    ]
    report["provisional_accepted_pair_count"] = len(constraints)
    report["supported_pair_count"] = len(supported_constraints)
    if not supported_constraints:
        report.update(
            status="gps_only",
            accepted_pair_count=0,
            refined_image_count=0,
            gps_only_image_count=len(placements),
            reason="Accepted matches did not form a mutually supported component of at least three images.",
        )
        emit("Accepted pair matches lacked three-image support; retaining GPS placement for every image.")
        return {item.name: (item.center_x, item.center_y) for item in placements}, report

    initial_x = np.asarray([item.center_x for item in placements], dtype=np.float64)
    initial_y = np.asarray([item.center_y for item in placements], dtype=np.float64)
    x_edges = [(i, j, item["dx"], item["weight"]) for i, j, item in supported_constraints]
    y_edges = [(i, j, item["dy"], item["weight"]) for i, j, item in supported_constraints]
    solved_x = _solve_axis(initial_x, x_edges)
    solved_y = _solve_axis(initial_y, y_edges)
    refined: dict[str, tuple[float, float]] = {}
    image_records: dict[str, Any] = {}
    connected = supported_nodes
    for index, placement in enumerate(placements):
        correction = float(np.hypot(solved_x[index] - initial_x[index], solved_y[index] - initial_y[index]))
        limit = max(50.0, min(placement.width, placement.height) * 0.30)
        accepted = index in connected and correction <= limit
        center = (float(solved_x[index]), float(solved_y[index])) if accepted else (placement.center_x, placement.center_y)
        refined[placement.name] = center
        image_records[placement.name] = {
            "status": "refined" if accepted else "gps_only",
            "initial_center_px": [round(placement.center_x, 6), round(placement.center_y, 6)],
            "final_center_px": [round(center[0], 6), round(center[1], 6)],
            "correction_px": round(correction if accepted else 0.0, 6),
        }
    refined_count = sum(1 for item in image_records.values() if item["status"] == "refined")
    report.update(
        status="refined",
        accepted_pair_count=len(supported_constraints),
        refined_image_count=refined_count,
        gps_only_image_count=len(placements) - refined_count,
        images=image_records,
    )
    emit(
        f"Global overlap solution accepted: {len(supported_constraints)} mutually supported pair(s), "
        f"{refined_count}/{len(placements)} image centre(s) refined; remaining images retain GPS placement."
    )
    return refined, report
